# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/anny/Nthu_10601/HardwareDesign/lab7/lab7.cache/wt [current_project]
set_property parent.project_path D:/anny/Nthu_10601/HardwareDesign/lab7/lab7.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/anny/Nthu_10601/HardwareDesign/lab7/lab7.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/anny/Nthu_10601/HardwareDesign/lab7/lab7.srcs/sources_1/imports/lab7/Music.v
  D:/anny/Nthu_10601/HardwareDesign/lab7/lab7.srcs/sources_1/imports/lab7/Music2.v
  D:/anny/Nthu_10601/HardwareDesign/lab7/lab7.srcs/sources_1/imports/lab7/PWM_gen.v
  D:/anny/Nthu_10601/HardwareDesign/lab7/lab7.srcs/sources_1/imports/lab7/PlayerCtrl.v
  D:/anny/Nthu_10601/HardwareDesign/lab7/lab7.srcs/sources_1/imports/lab7/debounce.v
  D:/anny/Nthu_10601/HardwareDesign/lab7/lab7.srcs/sources_1/imports/lab7/onepulse.v
  D:/anny/Nthu_10601/HardwareDesign/lab7/lab7.srcs/sources_1/imports/lab7/TOP.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/anny/Nthu_10601/HardwareDesign/lab7/lab7.srcs/constrs_1/imports/lab7/constraints.xdc
set_property used_in_implementation false [get_files D:/anny/Nthu_10601/HardwareDesign/lab7/lab7.srcs/constrs_1/imports/lab7/constraints.xdc]


synth_design -top TOP -part xc7a35tcpg236-1


write_checkpoint -force -noxdef TOP.dcp

catch { report_utilization -file TOP_utilization_synth.rpt -pb TOP_utilization_synth.pb }
